[tool.poetry]
name = "mychatgpt"
version = "0.1.0"
description = "Simple ChatGPT telegram bot"
authors = ["saintiago"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
