AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple app deployed on AWS Lambda

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 60
      Events:
        Webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST